### ISSUE TITLE
Show expired status on account page

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/theme#103]
When a license is expired, it doesn't show as expired on the account page.

This license is actually expired: https://annotate.driftt.com/view?i=l0w601mqm2nohro%2F2015-07-30_at_3.14_PM.png%2F

**Comment by pippinsplugins** [comment]
@sumobi if you design how you want it to show up, I'll build it.

We need to do this really soon.

**Comment by sumobi** [comment]
@pippinsplugins what about something like this. I can make further adjustments after it's done
![screen shot 2015-07-31 at 10 48 42 am](https://cloud.githubusercontent.com/assets/52581/8997092/ca245bee-3771-11e5-80fe-3f4764466426.png)

Maybe a "Click here to renew your license" link?

**Comment by pippinsplugins** [comment]
Looks good to me. What about also showing a banner somewhere on the site to really help encourage people to renew?

**Comment by sumobi** [comment]
Something like what we do for notifications and make it dismissible? or is that too aggressive. We could do a banner at the very top of the account page? first thing they see when they log in.

Give me a has_licenses_expired() function and I'll put something together

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/EDD-Site/issues/572

**Comment by sumobi** [comment]
Nice

**Comment by sumobi** [comment]
Banner is done:
https://github.com/affiliatewp/theme/tree/issue/103

![screen shot 2015-08-05 at 2 13 25 pm](https://cloud.githubusercontent.com/assets/52581/9076914/34226f1e-3b7c-11e5-8289-e07b44f16b1b.png)

Just need to add some expired text to licenses on the account page.

**Comment by sumobi** [comment]
Note: if there's another notice that we add for special events or such, it will temporarily override the expiry banner if the user has an expired license.

**Comment by pippinsplugins** [comment]
That looks awesome!

**Comment by sumobi** [comment]
Here's the notice on the account page

![screen shot 2015-08-22 at 9 40 11 pm](https://cloud.githubusercontent.com/assets/52581/9423405/772a78fe-4916-11e5-98ae-fa1508d5bbbb.png)

**Comment by pippinsplugins** [comment]
:+1:
