### ISSUE TITLE
New screenshots for emails needed

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/theme#104]
There should be some new screenshots for: email settings tab, and also the actual emails sent out

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
Going to wait until v1.7 is released before I make any screenshots

**Comment by wordmaid** [comment]
:+1: :ok_hand:

**Comment by sumobi** [comment]
This was added when the new site launched, closing
