### ISSUE TITLE
Suggestion: Add 'value' of license bundles to homepage/pricing page

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/theme#105]
It could be useful to put a "value" against/under each of the license options on the homepage and pricing page. This could really help to promote the excellent value of the top-tier licenses, which I'm not sure a lot of potential customers understand. I've considered a couple of things before suggesting this:

- There are quite a few support tickets asking why pro add-ons aren't sold separately, so this may not be clear enough at each point of purchase. Adding this in the pricing tables could save some support time and be more clear for customers. Here is a ticket example from today: https://secure.helpscout.net/conversation/111275185/14508/
   - As the pricing table compares the four license tiers, this could be a good place to clearly show that the Personal and Plus licenses don't include access to the pro add-ons

- Showing the value:- I noticed in the saved reply that the add-ons (if sold separately) would be approx. $40-$60 each. You could multiply the number of add-ons by the average cost per pro add-on to determine the value of add-ons included in the license. By showing this value, customers will be able to clearly see what they are getting for their money.

Would be more than happy to help put some math behind it. :)

**Comment by pippinsplugins** [comment]
@wordmaid I'd love to hear your thoughts on _why_ it's not clear that pro addons are not sold separately. I've looked at it so many times, I can't see why people ever misunderstand it. Any insights?

**Comment by wordmaid** [comment]
@pippinsplugins From my perspective it's just not clear enough on the website. I've seen customers compare AffiliateWP to other plugins that sell their add-ons separately in tickets. By showing them the value of the pro add-ons, they'll begin to understand that $199 or $449 is absolutely worth spending for the $1k value (or whatever it is). Some small changes could be made that may remedy this:

- The question on pro add-ons in the Pricing page FAQ could be moved closer to the top and re-worded slightly (eg. "I want pro add-ons, can I buy them for my Personal or Plus license?")

- In the comparison table, add "No pro add-ons" to the Personal and Plus license copy, and move "9 professional add-ons" to the top of the features list.

- The doc (http://docs.affiliatewp.com/article/132-which-licenses-can-access-the-pro-add-ons) could be fleshed out to be more clear (I'm happy to do this)

- <i>Side note: add a "Best value" note above the Ultimate license, similar to the "recommended" note.

**Comment by pippinsplugins** [comment]
Excellent,excellent points!

**Comment by pippinsplugins** [comment]
@sumobi :D

**Comment by wordmaid** [comment]
:+1:

**Comment by sumobi** [comment]
@wordmaid @pippinsplugins 

1. I've moved the pro add-ons text to the top of each pricing table. @wordmaid and I discussed this some more and we decided to not include "no pro add-ons" on the Personal and Plus license for now.
2. @wordmaidprovided some updated text for the clause underneath the pricing table that includes a note about pro add-ons
3. The pro add-on pages have updated copy depending on whether you have a personal or plus license, or are logged out. It's now clearer that pro add-ons cannot be purchased separately, and that if you are on the other licenses you must upgrade to access these.
4. The "Can I purchase the Pro Add-ons separately?" question has been moved 1 spot closer to the top of the pricing FAQs

**Comment by wordmaid** [comment]
@sumobi :raised_hands: Excellent time to do so as well!

**Comment by pippinsplugins** [comment]
Looks excellent!

**Comment by sumobi** [comment]
Closing now that the new site has an updated pricing table.
