### ISSUE TITLE
Move to EDD SL upgrade system

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/theme#107]
This involves several things:

- [ ] Remove current upgrade system
- [ ] Add upgrade paths to AffiliateWP product
- [ ] Change current upgrade links to use new upgrade URLs

**Comment by pippinsplugins** [comment]
Upgrade paths are created as such:
![screen shot 2015-09-23 at 8 39 17 pm](https://cloud.githubusercontent.com/assets/1034109/10063432/350576aa-6233-11e5-86f4-da38daa09825.png)

**Comment by pippinsplugins** [comment]
To retrieve the URL an upgrade, it is:
```php
$url = edd_sl_get_license_upgrade_url( $license_id, $upgrade_id );
```
The upgrade path IDs start from 1 and go up, so:

- Plus: 1
- Professional: 2
- Ultimate: 3

**Comment by pippinsplugins** [comment]
@sumobi I've gone ahead and done this (was pretty quick).

Could you please test the upgrades in your account on the dev site? I've tested it and it appears to work perfectly.

If it works, PR above.

One thing I noticed: 

https://github.com/affiliatewp/theme/blob/master/includes/edd.php#L800
https://github.com/affiliatewp/theme/blob/master/includes/edd.php#L800

That modal is displayed on the account page. The URLs in that modal won't work (nor do they work on previous upgrade system).

Are we sure that modal is still working on live? I wasn't able to get the modal to popup even.

**Comment by sumobi** [comment]
@pippinsplugins the license modal thingie is shown on single download pages (not the account page) to users that have a personal or plus license. Last time I checked they worked fine but will test again with the new stuff.

**Comment by pippinsplugins** [comment]
Based on the way the get URL function worked (and now works), it really couldn't have worked properly. At l east not in any way that I can see.

**Comment by sumobi** [comment]
@pippinsplugins I've run through some upgrades on the dev site and it works great

**Comment by sumobi** [comment]
@pippinsplugins Hmm, the upgrade links used the affwp_get_license_upgrade_url() function which you added :) I did test them at the time so they should have worked fine.

What links can we use now?

![screen shot 2015-09-26 at 9 50 56 pm](https://cloud.githubusercontent.com/assets/52581/10116930/cb8942fc-6498-11e5-8971-c372f726ee6d.png)

**Comment by pippinsplugins** [comment]
We can use the exact same ones shown in the account page. We'll just need to loop over the license keys in the same way. I'd say just copy and paste the code over.

**Comment by sumobi** [comment]
@pippinsplugins See: https://github.com/affiliatewp/theme/commit/2f6210622dd0f2ab742f8b36f800e9b095a8c3d9

Think we're good to go on this. Here's the new modal:

![screen shot 2015-09-28 at 10 23 57 pm](https://cloud.githubusercontent.com/assets/52581/10132100/30135df4-6631-11e5-9d35-10c2f6c215cb.png)

**Comment by pippinsplugins** [comment]
@sumobi Excellent. I'm going to deploy it to live.

**Comment by pippinsplugins** [comment]
it's live!
