### ISSUE TITLE
Add Active Installs data from WordPress.org to free add-ons

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/theme#111]
It would be cool to show the Active Installs data from WordPress.org on the free AffiliateWP add-ons pages, in the sidebar (I know that Easy Digital Downloads already has this). Thoughts?

**Comment by sumobi** [comment]
:+1: I like that idea. Did something similar for @pippinsplugins' site https://pippinsplugins.com/products/easy-digital-downloads/

**Comment by pippinsplugins** [comment]
Excellent idea :+1:

**Comment by michaelbeil** [comment]
:cat:

**Comment by sumobi** [comment]
This is done for new site
