### ISSUE TITLE
Affiliate table floats offscreen

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/theme#113]
This table is going to space: http://beil.io/1lUC9.

**Comment by sumobi** [comment]
we got a floater

**Comment by michaelbeil** [comment]
ewwww

**Comment by michaelbeil** [comment]
Occurs when there is a friggin long URL: http://beil.io/1cnLi.

**Comment by michaelbeil** [comment]
Otherwise, looks quite normal: http://beil.io/UzrR.

**Comment by michaelbeil** [comment]
Appears to happen whenever en dashes are not present in the URL: `http://affiliatewp.com/?utm_content=bufferea6aa&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer` vs. `http://affiliatewp.com/new-stripe-payouts-add-on-now-available/`

http://beil.io/11TT8 vs. http://beil.io/1dmX8

**Comment by sumobi** [comment]
it might be something we look at fixing in the plugin too, i think I know how to fix it

**Comment by michaelbeil** [comment]
This has been fixed in core: https://github.com/AffiliateWP/AffiliateWP/issues/933.
