### ISSUE TITLE
Add Screenshots as a top level menu item

### ISSUE THREAD

**Issue by wordmaid** [affiliatewp/theme#118]
Adding the plugin's screenshots as a top level menu item would increase the visibility of the screenshots section of the website (like the RCP website). It could also help with common pre-sale questions since customers will be able to see the functionality of the plugin before they open a ticket.

**Comment by sumobi** [comment]
:+1: I like that idea. The screenshots page is already the 3rd most visited page, if we make it more visible it could really shoot up and lead to more sales. @pippinsplugins ?

**Comment by pippinsplugins** [comment]
I'm all for it

**Comment by sumobi** [comment]
Done, might need to refresh thy browser 
![Uploading Screen Shot 2015-10-29 at 6.51.59 PM.png…]()

**Comment by michaelbeil** [comment]
yes! and yes more.
