### ISSUE TITLE
Separate add-ons into a page each for Pro, Free, and 3rd-party

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/theme#119]
This has possibly been discussed before, but I’d like to plead a case for giving the pro add-ons (and the free and 3rd-party add-ons) their own page.

In my dreamworld, when visitors hover on the Add-ons icon at the top, there would be a drop-down menu where they can choose to go and view the Pro add-ons, the Free add-ons, or the 3rd-party add-ons. If they click directly on the Add-ons icon, they would land on a page which then links them off to each of the pages (pro, free, 3rd-party). Same design as the current website - here’s my hack version of how it could look: https://cloudup.com/cFRGzHhjY0v (ignore the images, these would be updated to be relative to each category).

Here’s why I think I each category of add-ons needs its own page:

- We can put more of a sell/spin on the pro add-ons page to really hammer home the value that so many customers don’t understand
- We can be more explicit that pro add-ons are only available with Professional and Ultimate licenses, and are not for sale separately
- We can link to the Pro add-ons page from the pricing table on the Pricing page for the Professional and Ultimate licenses (when these inclusions are moved to the top of the features list)
- If we still need to rationalize the (~$50) value of each of the pro add-ons for pre-sale questions or customers who say they “only need one", we can link directly to the pro add-ons page and explain that customers receive access to all of the current pro add-ons, plus any built in the future. PLUS we can show them a whole page of the free add-ons they already have access to
- 3rd-party add-ons would have their own space, and I would also suggest adding a support/contact link or form on each 3rd-party add-on page as well.

If you guys agree this could be a good idea, I’m keen to help write up the copy for each page!

**Comment by sumobi** [comment]
:+1: I like that

**Comment by pippinsplugins** [comment]
I support all of this.

**Comment by sumobi** [comment]
Closing this since the updates are now live
