### ISSUE TITLE
Slashed pricing experiment

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/theme#120]
@pippinsplugins Now that we've made some changes to the pricing table (https://github.com/AffiliateWP/theme/issues/105#issuecomment-159493819) it seems like we may be spoiling our current experiment. Is it time to review our slashed pricing experiment and made a decision? 

Looking at the results so far, there isn't a clear winner, although the slashed pricing experiment shows improvements across the board. Looks like we should keep it this way. How about we run a new experiment on the homepage? (same test).

**Comment by pippinsplugins** [comment]
Whoops, missed this. I vote we go ahead and keep Professional slashed and disable the experiment.

**Comment by sumobi** [comment]
@pippinsplugins :+1: want to run it on the homepage?

**Comment by pippinsplugins** [comment]
We've disabled this now so closing.
