### ISSUE TITLE
Add big upgrade button on main tab of account page

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/theme#129]
Customers that can upgrade their license key should be shown a large upgrade notice front-and-center on the main tab of the account page.

**Comment by sumobi** [comment]
Noted for new site

**Comment by sumobi** [comment]
@pippinsplugins Any suggestions for the text? This is what I currently have:

> Upgrade your license and receive a pro-rated discount. Click the "View Upgrades" link below to continue.

![screen shot 2016-08-21 at 4 41 07 pm](https://cloud.githubusercontent.com/assets/52581/17835362/2cc4b6c2-67be-11e6-846d-aba377f1040f.png)

Notice will only show if an upgrade is available, and will show the same text (perhaps we can change this later) for customers that have 1 or multiple licenses. Perhaps for customers with 1 license we can instead show a "Upgrade license" button in place of the notice, but keep the notice for customers with multiple licenses.

**Comment by pippinsplugins** [comment]
I like that as is

**Comment by sumobi** [comment]
Ok cool
