### ISSUE TITLE
Survey svg notice div  

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/theme#130]
![screen shot 2016-06-07 at 2 33 50 pm](https://cloud.githubusercontent.com/assets/4752949/15872030/0065cefe-2cbd-11e6-9bc4-22f3cf202384.png)

**Comment by michaelbeil** [comment]
![screen shot 2016-06-07 at 2 36 31 pm](https://cloud.githubusercontent.com/assets/4752949/15872088/415b3f2a-2cbd-11e6-827c-f99edd42abb6.png)

**Comment by sumobi** [comment]
@michaelbeil what is the issue here? the space above the message? no icon?

**Comment by michaelbeil** [comment]
spacing

**Comment by michaelbeil** [comment]
appears like the svg is throwing a notice in the dev console:
`Unsafe attempt to load URL https://7386-presscdn-0-40-pagely.netdna-ssl.com/wp-content/themes/affiliatewp-master/images/svg-defs.svg from frame with URL https://affiliatewp.com/. Domains, protocols and ports must match.`

it does not seem like the svg is still present in the theme dir: 
https://github.com/AffiliateWP/theme/blob/master/images/svg-defs.svg
https://raw.githubusercontent.com/AffiliateWP/theme/master/images/svg-defs.svg

I see one tiny pixel: http://codepen.io/michaelbeil/pen/BzoeEa?editors=1000

**Comment by sumobi** [comment]
Fixed
