### ISSUE TITLE
Add Restrict Content Pro to "Our Sites" in footer

### ISSUE THREAD

**Issue by mindctrl** [AffiliateWP/theme#131]
![image](https://cloud.githubusercontent.com/assets/1254870/15936760/347e8d06-2e3a-11e6-8a38-67836d73df91.png)

**Comment by michaelbeil** [comment]
I think this might be in the new site design.

**Comment by sumobi** [comment]
It is, I can add it to the current one also

**Comment by michaelbeil** [comment]
Could add the affiliate link as well.

**Comment by sumobi** [comment]
yepp
