### ISSUE TITLE
Add new pricing FAQ about "sites"

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/theme#132]
I've seen numerous customers asking us what a "site" is. They think it means how many affiliate sites can link to their site, not how many sites they can use AffiliateWP on. I think we should add a new FAQ on the pricing page to clear this up.

> Also for your $99 licence - it refers to being limited to 3 sites - do they mean 3 affiliate sites?

**Comment by wordmaid** [comment]
> **What is a "site"?**
> 
> In our pricing above, a "site" refers to the number of WordPress websites you can use AffiliateWP on (you can have an unlimited number affiliates promoting your website).

**Comment by michaelbeil** [comment]
I would add of here:  
> unlimited number affiliates 

So it is ...
> unlimited number of affiliates 

This will be a great addition, although, now we will need to another FAQ to even out the template, or could just center it at the bottom of the two columns, or I guess let the symmetry slide.

**Comment by sumobi** [comment]
This has been added to new site 👍
