### ISSUE TITLE
Remove affwp_edd_auto_create_user()

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/theme#133]
We use the EDD Auto Register plugin so no longer need `affwp_edd_auto_create_user()`.

It's adding unneeded load to the purchase process.

**Comment by sumobi** [comment]
I wonder if it's also conflicting with auto register 👍

**Comment by sumobi** [comment]
Fixed via https://github.com/AffiliateWP/theme/commit/998c26d323a0c372cd4a8422120948061f44feb6
