### ISSUE TITLE
About menu name changed to "Meet the AffiliateWP team"

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/theme#136]
In https://github.com/AffiliateWP/theme/blob/master/includes/custom-filters.php#L58 we have a title set for the about page template: **Meet the AffiliateWP team**. The edit page screen for `about` reads **About**, however the menu item can no longer be changed to **About** since we updated to WordPress 4.5.3 today.
![screen shot 2016-07-21 at 10 56 44 am](https://cloud.githubusercontent.com/assets/4752949/17030314/934eab48-4f34-11e6-8e4e-47bdd6b323bb.png)

I am thinking that we could change the page name to **Meet the AffiliateWP team** from the edit page screen, and then change the menu item to **About**, removing the template name override altogether.

**Comment by sumobi** [comment]
Nice 👍  Fixed
