### ISSUE TITLE
Add system info uploader to the support page

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/theme#137]
Now that https://github.com/AffiliateWP/AffiliateWP/issues/1413 is in core, we should add a required sys info upload field on the support page.

**Comment by michaelbeil** [comment]
Pinging @sumobi now that the new site is up. I could add this too if you like.

**Comment by michaelbeil** [comment]
Added system info. We should make it required in a few months.

**Comment by sumobi** [comment]
👍

**Comment by sumobi** [comment]
This was added some time ago
