### ISSUE TITLE
Highlight Failing subscriptions

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/theme#145]
When a customer has a subscription that is marked as `Failing` (card declined during renewal or similar), we need to highlight it on the account page to help it easier for them locate the "Update Payment Method" link.

License keys associated with a failing subscription will be marked as expired and will show links to renew the license. This makes it seem like the customer should renew the license but really they need to visit the `Subscriptions` tab and click `Update Payment Method`.

![screen shot 2017-01-21 at 9 04 24 am](https://cloud.githubusercontent.com/assets/1034109/22175364/d2011b04-dfb8-11e6-8cef-5bad73b8b634.png)

![screen shot 2017-01-21 at 9 05 45 am](https://cloud.githubusercontent.com/assets/1034109/22175365/d58187a0-dfb8-11e6-9596-5775e2fa9aed.png)

**Comment by pippinsplugins** [comment]
Failing subscriptions can be retrieved like this:
```php
$subscriber = new EDD_Recurring_Subscriber( get_current_user_id(), true );
$failing_subs = $subscriber->get_subscriptions( 0, 'failing' );
```

The update payment method URL looks like this: 

https://affiliatewp.com/account/?action=update&subscription_id={sub_id}

I think I will work on some `Recurring Payments` improvements to automatically change the `Renew` link to a `Update Payment Method` link on the `License Keys` tab.

**Comment by pippinsplugins** [comment]
Tagging @sdavismedia for cross work on EDD site.

**Comment by pippinsplugins** [comment]
Will also need to do this on the RCP site.

**Comment by sumobi** [comment]
👍

**Comment by sumobi** [comment]
@pippinsplugins This is what I've added (keys aren't real below). I'll transfer over to RCP in the morning.

Most people will have 1 subscription:

![screen shot 2017-01-26 at 8 06 01 pm](https://cloud.githubusercontent.com/assets/52581/22322739/fccaa62c-e402-11e6-96b0-11bfc0258c60.png)

___

For those with more than 1, for whatever reason:

![screen shot 2017-01-26 at 8 06 11 pm](https://cloud.githubusercontent.com/assets/52581/22322738/fcab8dc8-e402-11e6-94c5-3209a3b13807.png)

**Comment by pippinsplugins** [comment]
I like that a lot.

**Comment by pippinsplugins** [comment]
Excellent. Deploy at will!

**Comment by sumobi** [comment]
Oh, did that last night, just linking up the commit :)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
sweet sweet

**Comment by sumobi** [comment]
RCP is done, closing
