### ISSUE TITLE
Update last updated date on pro add-ons

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/theme#150]
When viewing the free and pro add-on pages, not all of the Download meta data is on each add-on.  I especially like to see the Update date to know if the version number matches up.  

![add-on-download-data](https://user-images.githubusercontent.com/3018245/32338686-b96c9084-bfb2-11e7-8f07-35e8f441bd0e.png)

**Comment by amdrew** [comment]
@gspice Would you like to go through each pro add-on and add the last updated date? I've just fixed up the REST API Extended add-on: https://affiliatewp.com/add-ons/pro/rest-api-extended/

Last updated date can be found here: 

<img width="302" alt="screenshot 2017-11-03 10 29 10" src="https://user-images.githubusercontent.com/52581/32351332-da2d8ef2-c081-11e7-8428-53d0d5e6b868.png">

As for the other information, what else would you like to see? The information on official free add-ons is pulled directly from wp.org so not quite the same as pro add-ons. We can't show "active installs" for example, and I'm not sure if we would show "downloads". Looks like everything else is there.

**Comment by gspice** [comment]
@amdrew 
> Would you like to go through each pro add-on and add the last updated date? 

Yes!  That is specifically what I had in mind, the last updated date. I'll update these.  I forgot, regarding free add-ons, the info is pulled from wp.org.

**Comment by gspice** [comment]
Finished adding updated dates to all pro add-ons.

**Comment by amdrew** [comment]
@gspice Awesome 👍
