### ISSUE TITLE
Ensure Perfect Audience tracking only runs on production site

### ISSUE THREAD

**Issue by mindctrl** [AffiliateWP/theme#157]
We've seen some issues with weird conversion numbers, and the going theory is it's from someone's local dev environment.

We should add some kind of check [here](https://github.com/AffiliateWP/theme/blob/c9f8167e2272d2630de83524d630c2adb2c1d854/includes/scripts.php#L227) to ensure it only runs on the production site.

One idea is to simply do a constant defined check that we set in the production site's wp-config.php.

**Comment by mindctrl** [comment]
I don't see anything in the [functionality plugin](https://github.com/AffiliateWP/affwp-functionality) that needs updating.

**Comment by pippinsplugins** [comment]
Merged, deploy at will.
