### ISSUE TITLE
A/B Test Homepage slides

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/theme#26]
I love the slides but I would also be extremely intrigued to know whether slides or a static graphic (similar to Gravity Forms) converts better.

I can easily setup the A/B test to track the data.

@sumobi What do you think about setting up a static graph alternative that we can show to 50% of visitors?

**Comment by sumobi** [comment]
@pippinsplugins I've been thinking about this for quite some time and I've finally come to the conclusion that it might be a good experiment. Going to add it to Trello.
