### ISSUE TITLE
Style "Looking for our affiliate area?" and "Need to register an account?"

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/theme#69]
The links above the login form for the affiliate area and account registration (I just added [one](https://github.com/affiliatewp/theme/commit/4cce4f83e55d90110dd4415a1acd9c105bc1f752)) could use some love.

What about making them side-by-side buttons?

**Comment by michaelbeil** [comment]
This seems invalid with current site.

**Comment by sumobi** [comment]
Oh yeah we can close this
