### ISSUE TITLE
Download failed. Unauthorized

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/theme#94]
It seems that a couple of customers are having issues when upgrading the tiered rates add-on (it could be others also). 

    Download failed. Unauthorized.

@pippinsplugins has suggested it's a bug with the ultimate license

customer ticket: https://secure.helpscout.net/conversation/65216235/4976/

**Comment by sumobi** [comment]
@pippinsplugins It doesn't seem to be limited to the ultimate license, looks like the professional license is also affected. Here's another ticket: https://secure.helpscout.net/conversation/64843266/4930/

**Comment by pippinsplugins** [comment]
I think I've fixed this.

Was due to a change in Software Licensing that I forgot about.

**Comment by pippinsplugins** [comment]
Closing until we see another report (if we do).

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Could you install an old version on a site then try and update to test?

**Comment by sumobi** [comment]
@pippinsplugins Tried on sumobi.com but didn't work, same error. Using your unlimited license key

**Comment by sumobi** [comment]
Here's another ticket of this issue https://secure.helpscout.net/conversation/65630895/5039/

**Comment by pippinsplugins** [comment]
Fixed!
