### ISSUE TITLE
SSL unencrypted elements?

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/theme#95]
Firefox is showing this message. Console is not showing any messages. Chrome has the green lock, Safari shows nothing.

![screen shot 2015-01-22 at 7 05 51 pm](https://cloud.githubusercontent.com/assets/52581/5851278/c24a6096-a269-11e4-8669-22e4daa87829.png)

**Comment by michaelbeil** [comment]
All seems fine now. Shall we close this?

http://beil.io/lJo7
