### ISSUE TITLE
Integrations page

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/theme#98]
Rather than linking to the doc page on the homepage, we should have a prettier version on the site somewhere that shows logos etc.

**Comment by sumobi** [comment]
I like the idea of having a page for each integration, similar to what we're going to do for https://github.com/pippinsplugins/rcp-site-child/issues/35. 

This way you could click on the EDD logo and find a whole page of information it (great for SEO). On this page we could also list out all add-ons that support EDD, making it easier for customers to see what functionality will be available to them if EDD is their preferred system. Another idea is listing code snippets, tutorials or general blog posts that relate to this integration.

**Comment by pippinsplugins** [comment]
Yes yes yes.

**Comment by pippinsplugins** [comment]
It would also be a great place to include FAQs and other information for each FAQ.

**Comment by sumobi** [comment]
:+1: Customers who come to the AffiliateWP site will most likely already have a system in place that they are using, it would be fantastic to be able to provide them with all this information straight off the bat to help aid their purchasing decision.

**Comment by pippinsplugins** [comment]
Definitely. I love this.

**Comment by sumobi** [comment]
Integrations pages are complete for new site. Closing this issue. We can discuss any further ideas on the Trello card.
