### ISSUE TITLE
New homepage design

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/theme#99]
The homepage can be drastically improved however we need to a/b test the changes we make. 

I'm proposing we create a 2-3 complete designs and a/b test those alongside the current design. Another option is to slowly a/b test each little redesign but this could take some time. I think we should a/b complete redesigns and then based on those results we'll re-work the winner.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
New site has new homepage, let's close this and add any potential a/b tests to the Trello card
